### PR TITLE
[Marksmanship] Patient Sniper tab and statistic

### PR DESCRIPTION
**Pull request by Pewtro**
Adds a statistic box with average damage gain from Patient Sniper: 
image

Aswell as a tab with significantly more detailed information:
image

~~Also moves folders around to adjust for new Class/Spec structure~~
Also deletes ProcTracker as it is currently not used at all, and was just a copy of some shaman code.

### CODE REVIEW

**Comment by MartijnHols** [comment]
Both moving and renaming the folder and adding a new feature in the same PR is going to make reviewing this very difficult. You also have merge conflicts. I recommend making different PRs instead.

**Comment by Pewtro** [comment]
undid the movement and rename of folders, will add in a separate PR once this and focus module clears

**Comment by sMteX** [comment]
To update on this PR - I'm working with @Pewtro on a refactor of this to be more readable. We'll most likely to close this one and open a new one.

**Comment by sMteX** [comment]
A new, refactored PR was just open ( #575 ), closing this one.

**Pull request closed without merging**
