### PR TITLE
load routes asynchronously

### PR DESCRIPTION
**Pull request by ToppleTheNun**
### Description

Code split all of our app routes in order to reduce bundle sizes.

### Testing

Run the app, make sure it still works.

- Screenshot(s):
image
progressbar

### CODE REVIEW

**Comment by ToppleTheNun** [comment]
I still need to add a couple of small things to make navigation feel better while it's loading the next chunk.

**Review by emallson — CHANGES_REQUESTED** [review]
this is overall a really good improvement. i did some poking around locally and have two comments, basically:

1. we should include the Home and App layouts in the initial bundle. it doesn't inflate the bundle too much and means that you're not waiting on another network round trip for the landing page to display anything at all.
2. if we want to go even further, we should lazy-load Sentry. Vega is a pretty chunky dependency but is easy to lazy load. Sentry, tho, is currently in the main bundle and a sizable chunk of it: 
image


i looked a bit at lazy-loading sentry but it will require fucking around with redux state and i have *no idea* what lazy loading that looks like sooooo future project

**Comment by ToppleTheNun** [comment]
Bundle size changes as a result of re-adding HomeLayout and AppLayout to initial bundle:

Without
```
dist/assets/index-1KJ0usy-.js                                 193.34 kB │ gzip: 124.34 kB │ map:   245.66 kB
dist/assets/index-nrmj7pFf.js                                 269.25 kB │ gzip:  66.01 kB │ map:   663.28 kB
dist/assets/index-DNzr8jq1.js                                 470.57 kB │ gzip: 159.74 kB │ map: 2,172.26 kB
dist/assets/SpellLink-BvtgGhEe.js                             748.50 kB │ gzip: 194.09 kB │ map: 1,904.43 kB
dist/assets/CombatLogParser-CaspHTSM.js                     1,099.07 kB │ gzip: 359.37 kB │ map: 4,867.17 kB
```

With
```
dist/assets/CombatLogParser-Dx3Wdyp8.js                       233.78 kB │ gzip:  48.18 kB │ map:   755.47 kB
dist/assets/index-G-3g7YSF.js                                 268.12 kB │ gzip:  65.79 kB │ map:   663.28 kB
dist/assets/index-B1QUVTUk.js                                 529.69 kB │ gzip: 180.69 kB │ map: 2,386.54 kB
dist/assets/SpellLink-BVEexm6l.js                             748.46 kB │ gzip: 194.08 kB │ map: 1,904.43 kB
dist/assets/CombatLogParser-DAeQP7_b.js                     1,098.96 kB │ gzip: 359.34 kB │ map: 4,867.17 kB
```

I also reduced the Sentry bundle size slightly.

**Comment by emallson** [comment]
i think that seems worthwhile

**Review by emallson — APPROVED** [review]

**Comment by ToppleTheNun** [comment]
with Sentry dynamically imported, but with Redux included:
```
dist/assets/CombatLogParser-y5jTf3U4.js                       233.78 kB │ gzip:  48.19 kB │ map:   755.47 kB
dist/assets/index-Du_0YTCe.js                                 268.12 kB │ gzip:  65.78 kB │ map:   663.28 kB
dist/assets/index-BimsJdJc.js                                 529.37 kB │ gzip: 180.49 kB │ map: 2,384.87 kB
dist/assets/SpellLink-BolAmOTO.js                             748.46 kB │ gzip: 194.08 kB │ map: 1,904.43 kB
dist/assets/CombatLogParser-DEjDjTO8.js                     1,098.96 kB │ gzip: 359.33 kB │ map: 4,867.17 kB
```

**Comment by ToppleTheNun** [comment]
Copying this here too because it's relevant:
> it's also worth noting that we don't really need the redux integration in Sentry
> it also has the potential to include unholy amounts of data because we're shoving the entire current report into redux
> and it also turns out that lazy loading Sentry doesn't really work because we use it in our root error boundary
> so unless we refactor that too, we can't really get away from it

**Pull request merged**
