### PR TITLE
[BFA Resto Druid] Clean up

### PR DESCRIPTION
**Pull request by karlpralow**
Removed deleted abilities, artifact traits and netherlight crucible traits

### CODE REVIEW

**Comment by emallson** [comment]
We don't know yet whether we'll have artifact traits and abilities in pre-patch. If you put the traits back in we can get spell changes merged.

**Comment by kfinch** [comment]
Hey sorry I haven't looked at this, been 2 weeks of hell at work and haven't had time for anything. These removals look reasonable, though I agree with emallson that you should hold off removing trait stuff for now.

**Comment by Gebuz** [comment]
Should be good to merge this now that PTR confirms that traits are gone in prepatch, just need to resolve the merge conflict

**Comment by kfinch** [comment]
Yeah, this looks fine to me, thanks for picking this up! I think possibly removing something that gets added back wouldn't be a disaster, worst case you just dig it back out of git history. 

I've been inactive so you can feel free to do whatever you want to bring Resto up to speed for BfA. If you have questions about existing code, feel free to @ me on Discord or GitHub.

**Pull request merged**
