### PR TITLE
enable camelcase lint rule

### PR DESCRIPTION
**Pull request by Zeboot**
Most instances are either API objects (which obviously stay that way so gained exceptions), or the fight interface which will be fixed when the files in question get converted to TS, dropping the proptypes for the actual interface

### CODE REVIEW

**Comment by Dambroda** [comment]
offset_time is not from any API and could be renamed (EDIT: wait didnt you add that? 🤔 )

**Comment by Zeboot** [comment]
yap :D left that one more cause it fits the current parameters of fight to keep it similar (and cause it already has an exception defined to it by zero) (see "or the fight interface" in the original post ;) )

**Comment by Dambroda** [comment]
Im not blocking, but if anything I think it *shouldn't* match the WCL format as its not a WCL field (for the fight interface as well)

**Review by Dambroda — APPROVED** [review]

**Review by MartijnHols — APPROVED** [review]
My hero!

**Review by abelito75 — APPROVED** [review]
My Hero!

**Pull request merged**
