### PR TITLE
Resto Druid analysis for Classic

### PR DESCRIPTION
**Pull request by Arbixal**
### Description

I'm sorry, my PR got bigger than I intended.
I added Lifebloom, Rejuvenation, Swiftmend, Wild Growth, and Revitalize analyzers for Classic Resto Druid spec.
I added the guide style to Resto druid as default.
I changed the guide to be a little more open to Wrath Classic.

### Motivation

Wanted a resto druid analyzer for classic.

### Testing

Check that retail guides aren't broken (shouldn't be).
Check that classic checklist for preparation still works as intended.
Load up a classic resto druid report.

Classic Resto Druid Analysis - Overview
Classic Resto Druid Analysis - Statistics
Screenshot 2023-01-30 132053

### CODE REVIEW

**Comment by kfinch** [comment]
Skimmed it and looks good from what I've seen - could you attach a screenshot of how it looks as well?

**Comment by Arbixal** [comment]
I'll post some more screenshots a little later. These are what I have with me.
image

image-1

Screenshot 2023-01-28 152526

Screenshot 2023-01-28 152505

Screenshot 2023-01-28 152546

image-1

Takes a lot of inspiration from Retail Resto Druid.

**Comment by Arbixal** [comment]
Is there anything else I need to provide for this?

**Review by ToppleTheNun — APPROVED** [review]
Verified things still work for retail across a few different logs

**Pull request merged**
