### PR TITLE
Add all DK and Paladin Legendaries

### PR DESCRIPTION
**Pull request by fyruna**
Intermediate steps for issue #388: List all Legendaries in items

There were 0 legendaries for DK's listed so I added them all and added all missing legendaries for Paladin.

### CODE REVIEW

**Comment by kfinch** [comment]
"style" :wheelchair:

**Comment by sMteX** [comment]
Related to #505

**Comment by fyruna** [comment]
Did the suggestion by @kfinch and I think what @sMteX is suggesting is a good idea.

**Comment by sMteX** [comment]
Feel free to push the PR still to the unified ITEMS.js, I could take on the issue of separating it myself after you merge :)

**Comment by fyruna** [comment]
It's good to be rechecked by @kfinch or someone else.

**Comment by kfinch** [comment]
Comments send me a notification, so I saw, but I was in my car. Also, since I so callously demanded changes it actually requires that I approve them before it can be merged. 😄

**Pull request merged**
