### PR TITLE
Windwalker: fix checklist error when using chi wave

### PR DESCRIPTION
**Pull request by awiss**
### Description

I encountered this error during development when I attempted to load a log where I had chi wave talented.
```
Error: GenericCastEfficiencyRequirement requires that you pass the castEfficiency object yourself. Spell: 115098
    at get thresholds [as thresholds] (http://localhost:3000/static/js/src_parser_retail_modules_features_Checklist_PreparationRule_tsx-src_parser_shared_modules_fe-65291a.chunk.js:288:76)
    at GenericCastEfficiencyRequirement.render (http://localhost:3000/static/js/src_parser_retail_modules_features_Checklist_PreparationRule_tsx-src_parser_shared_modules_fe-65291a.chunk.js:333:29)
    at finishClassComponent (http://localhost:3000/static/js/bundle.js:157697:35)
    at updateClassComponent (http://localhost:3000/static/js/bundle.js:157650:28)
    at beginWork (http://localhost:3000/static/js/bundle.js:159235:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:144200:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:144249:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:144309:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:164051:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:162887:16)
```

My fix is changing the spell ID in Abilities.tsx from `SPELLS.CHI_WAVE_TALENT_DAMAGE.id` to `TALENTS_MONK.CHI_WAVE_TALENT.id`.

Not 100% sure if this is the right fix or if I'm missing something here but it does resolve the error and the checklist counts the casts correctly.

### Testing

This report errors on the `dragonflight` branch, does not on this branch.

- Test report URL: `/report/vkb8nPmxa1BNKq6t/3-Heroic+Terros+-+Kill+(3:34)/Tenooki/standard/overview`
- Screenshot(s):

### CODE REVIEW

**Comment by awiss** [comment]
I'm aware there is a lot more work to do to get WW up and running, just starting here to get some initial experience contributing.

**Review by trevorm4 — APPROVED** [review]

**Comment by trevorm4** [comment]
lgtm, this is the correct way of fixing it. Thanks for the first pr!

**Comment by awiss** [comment]
Just noticed an issue! Can you remove from merge queue?

**Comment by Pewtro** [comment]
Removed

**Comment by awiss** [comment]
Thanks. Added to the main changelog, not the windwalker one. It's fixed now.

**Comment by Pewtro** [comment]
Set it to auto, so you don't have to do anything (assuming ci passes)

**Pull request merged**
