### PR TITLE
i18n: add ids to older i18n code

### PR DESCRIPTION
**Pull request by jos3p**
- Adding IDs to all \<Trans\> or t\`...\`
- Adding tags to tooltips to make it consitent

Status:

- [x] PremiumPage + PremiumLoginPanel camelCase fixed.
<details>
<summary> ./src/interface/* (done) </summary>

- [x] ./src/interface/ReportSelecter.tsx
- [x] ./src/interface/report/PatchChecker.js
- [x] ./src/interface/report/PlayerLoader.js
- [x] ./src/interface/report/FightSelection.js
- [x] ./src/interface/report/SupportChecker.js
- [x] ./src/interface/report/ClassicLogWarning.tsx
- [x] ./src/interface/report/ReportDurationWarning.tsx
- [x] ./src/interface/report/Results/Timeline/Buffs.js
- [x] ./src/interface/report/Results/Timeline/Casts.js
- [x] ./src/interface/report/Results/Timeline/Lane.js
- [x] ./src/interface/report/Results/index.js
- [x] ./src/interface/report/Results/Statistics.js
- [x] ./src/interface/GuildReports/GuildReports.tsx
- [x] ./src/interface/HelpWantedPage/HelpWantedPage.tsx
- [x] ./src/interface/others/ReportSelecter.js
- [x] ./src/interface/CharacterParses/CharacterParses.js
- [x] ./src/interface/home/ReportSelectionHeader.js
- [x] ./src/interface/home/ReportHistory/index.js
- [x] ./src/interface/AboutPage/AboutPage.tsx
- [x] ./src/interface/Search.tsx

</details>
<details>
<summary> ./src/parser/**NOTPALADIN**/* (done) </summary>

- [x] ./src/parser/shaman/restoration/modules/features/StatValues.js
- [x] ./src/parser/shaman/restoration/modules/features/checklist/Component.tsx
- [x] ./src/parser/shaman/enhancement/modules/core/FlametongueRefresh.tsx
- [x] ./src/parser/shaman/enhancement/modules/core/Flametongue.tsx
- [x] ./src/parser/shared/modules/CastEfficiency.tsx
- [x] ./src/parser/monk/windwalker/modules/items/LastEmperorsCapacitor.js
- [x] ./src/parser/monk/mistweaver/modules/talents/InvokeChiJi.tsx
</details>
<details>
<summary> ./src/parser/paladin/* (done) </summary>

- [x] ./src/parser/paladin/holy/modules/azeritetraits/GlimmerOfLight.js
- [x] ./src/parser/paladin/holy/modules/CastBehavior.js
- [x] ./src/parser/paladin/holy/modules/FillerFlashOfLight.js
- [x] ./src/parser/paladin/holy/modules/StatValues.js
- [x] ./src/parser/paladin/holy/modules/MasteryEffectiveness.js
- [x] ./src/parser/paladin/holy/modules/Abilities.tsx
- [x] ./src/parser/paladin/holy/modules/checklist/Component.js
- [x] ./src/parser/paladin/holy/modules/talents/DevotionAuraDamageReduction.js
- [x] ./src/parser/paladin/holy/modules/talents/CrusadersMight.js
- [x] ./src/parser/paladin/holy/modules/talents/RuleOfLaw.js
- [x] ./src/parser/paladin/holy/modules/beacons/MissingBeacons.js
- [x] ./src/parser/paladin/holy/modules/beacons/BeaconHealingBreakdown.js
- [x] ./src/parser/paladin/holy/modules/beacons/BeaconUptime.js
- [x] ./src/parser/paladin/holy/modules/beacons/DirectBeaconHealing.js
- [x] ./src/parser/paladin/holy/modules/beacons/BeaconHealingDone.js
- [x] ./src/parser/paladin/holy/modules/beacons/FailedBeaconTransfers.js
- [x] ./src/parser/paladin/holy/modules/FillerLightOfTheMartyrs.tsx
- [x] ./src/parser/paladin/holy/modules/Overhealing.js
</details>

no more strings left to be marked.

### CODE REVIEW

**Comment by darya-talanina** [comment]
@jos3p If possible, I suggest splitting this work across several PRs to simplify review and reduce amount of conflicts.

**Comment by joshinat0r** [comment]
Should be fine as long as its just translation-stuff, he asked yesterday in Discord if it would be fine 👍

**Comment by Pewtro** [comment]
If you fix the conflict errors, I think this is good to go! Thanks for all this hard work!

**Comment by jos3p** [comment]
thank you, I resolved to conflicting messages.

**Comment by abelito75** [comment]
putput said its good so imma merge it

**Pull request merged**
