### PR TITLE
Added 'copy Pawn String to clipboard' button to StatValues panel

### PR DESCRIPTION
**Pull request by kfinch**
Zero help me! I have no idea how to CSS a button at all! This looks like garbage!

### CODE REVIEW

**Comment by kfinch** [comment]
Currently doesn't look like a button at all:

shitty-button

**Comment by kfinch** [comment]
OK I tried... Dunno how to make shift up a bit tho.

ok-button

**Comment by Pewtro** [comment]
``vertical-align`` maybe?

**Comment by kfinch** [comment]
Oh I think when I tried vertical align I put it as a class instead of a style because I was way too tired.

**Comment by MartijnHols** [comment]
I think a copy to clipboard solution would be a better suited as a function than a React component. This could also be done with a library, but probably not the one you're using now. Then you could just programmatically give feedback instead of using a focus-hack.

Also Travis is failing.

**Comment by kfinch** [comment]
@MartijnHols can you explain how a function would solve this? I'm having trouble envisioning what that would look like.

The Travis fail is just an imports thing, I knew this wasn't ready for merge so I just hadn't fixed it yet.

**Comment by MartijnHols** [comment]
Button onClick -> trigger method that calls the function to copy a string to clipboard & shows a toaster that it happened. I believe we want full control over how such a button looks like, so I think using a React component to do it seems undesirable.

**Comment by kfinch** [comment]
Good point, the React thing did seem awkward... Maybe I'm using the wrong library, but it wasn't obvious how to bind copying to a function. 

Also can you point to am example in code of this function binding? I dunno why, but I'm having real trouble thinking about what this would look like.

**Comment by MartijnHols** [comment]
https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript

**Comment by kfinch** [comment]
Hopefully I'll have time to get back to this and get this fixed before I go on vacation...

**Comment by kfinch** [comment]
I'll reimplement something that actually works some other time....

**Pull request closed without merging**
