### PR TITLE
[Augmentation] Fix undefined issue in Shifting Sands module

### PR DESCRIPTION
**Pull request by Krealle**
### Description

Some guy found a target with undefined buffs, now we default to `false` if that happens again.

### Testing

- Test report URL: `/report/qymghkvXH93fat4x/18-Mythic+Scalecommander+Sarkareth+-+Wipe+18+(7:30)/Dragoproject/standard/overview`

### CODE REVIEW

**Review by emallson — APPROVED** [review]
there's probably an underlying issue to fix there, but this is fine to just make it stop erroring

**Comment by Krealle** [comment]
@emallson guess you were right :)) any chance you could send a link to the log that is giving the error?

**Comment by ToppleTheNun** [comment]
@Krealle https://wowanalyzer.com/report/t6Nv7xz9XJy8DAdq/22-Heroic+Balakar+Khan+-+Kill+(0:53)/Modria/standard

**Comment by ToppleTheNun** [comment]
Simplest "fix" is to just put a `?` after target:
```
  private onCast(event: ApplyBuffEvent) {
    const target = this.combatants.players[event.targetID];

    const shiftingSandsApplication: ShiftingSandsApplications = {
      event: event,
      ebonMightOn: target?.hasBuff(SPELLS.EBON_MIGHT_BUFF_EXTERNAL.id) ?? false,
      prescienceOn: target?.hasBuff(SPELLS.PRESCIENCE_BUFF.id) ?? false,
      combatant: target,
    };

    this.shiftingSandsApplications.push(shiftingSandsApplication);
  }
```

Doesn't really handle the possible error cases from `combatant: target` being undefined, though.

**Comment by Krealle** [comment]
hmm, one of the players in the log is not in the combatant list, when I use `console.log(this.combatants.players);` I only get 4/5 players returned. The missing one being the one that is causing issues.

**Comment by Krealle** [comment]
Seems like it's completely broken for that player actually.
image

**Comment by ToppleTheNun** [comment]
This is included in that player's combatantinfo event in both the V1 API and the V2 API responses:
```json
{
  "error": "expected int but found [P]"
}
```

Not sure what that error means exactly, but it's why the character is blocked.

**Pull request merged**
