### PR TITLE
Down time update

### PR DESCRIPTION
**Pull request by yajinni**

### CODE REVIEW

**Comment by Gebuz** [comment]
Looks fine, but looking at the AlwaysBeCasting.js file I noticed that there is a lot of abilities listed as being on the GCD even though they are not. This will mess with the downtime, so I'll wait with merging this if you want to fix that first. Otherwise let me know and I'll just merge this. 

Ideally it should be fixed by updating to the new format where all abilities are listed in abilities.js and those that are on the GCD have the prop `isOnGCD: true,` (see holy paladin for an up to date example), but if you want a quick fix you could just remove the abilities not on GCD from the ABILITIES_ON_GCD array.

Just at a quick glance, all the cooldowns, all the CC except for Gorefiends, and about half the talents shouldn't be in the list. Also Asphyxiate is listed as the UH/frost talent instead of the blood one (different ID cause it aint a talent).

**Comment by Gebuz** [comment]
looks I was writing too slowly :D

**Comment by CollCrom** [comment]
Ah darn it I just saw your comment @gebuz

**Comment by Gebuz** [comment]
No worries, wasn't something that had to be in this PR.

**Pull request merged**
