### PR TITLE
[frost mage] Tier21 2pc and Mastery

### PR DESCRIPTION
**Pull request by kfinch**
Added support for Tier21 2pc. Flurry bolt tracking is a little try-hard because of delay issues, but I believe it will work correctly in nearly all situations, and will work close to correctly in very odd (high haste) situations.

I wanted to add the 4pc too, but haven't yet been able to find any logs with it.

Also added Frost Mage mastery ratios so that Mastery percent shows correctly on the stats pane.

### CODE REVIEW

**Comment by Sharrq** [comment]
Thanks! I kept telling myself i needed to get to that but first week of new raid has been a little crazy

**Comment by Pewtro** [comment]
It's good but needs a merge conflict fix

**Comment by kfinch** [comment]
I shouldn't have merged other people's Mastery implementations 😛

**Comment by kfinch** [comment]
@Pewtro 
I should say the fix is for a more rare a case than just "high haste", it's basically "high haste, and the player gets two procs in a row, and the player makes the (incorrect) choice to use them back to back"

Also please don't start the merge unless you're going to finish it, things are a little messed up on the branch now.

**Comment by kfinch** [comment]
Ok gottem

**Comment by Pewtro** [comment]
Yeah I did finish the original merge, then travis was slow so I moved onwards 😛

**Pull request merged**
