### PR TITLE
Player Selection UI Improvements

### PR DESCRIPTION
**Pull request by kyle-glick**
Referencing Issue https://github.com/WoWAnalyzer/WoWAnalyzer/issues/828.

Features:
1. Added role groups for better organization of players.
2. Added appropriate class colors to each player.
3. Added `className` sort to group players of the same class - recommended to me by a Guildie.
4. Maintained support for WCL error that causes player's spec to be undefined.

Still TODO:
1. Figure out how to get Player's realm

## Updated UI
image

## Class Sorting
image

## Spec Error from WCL
image

### CODE REVIEW

**Comment by MartijnHols** [comment]
Looks good (although I haven't looked into the code yet, maybe tomorrow), but from your screenshots:

- Could you make the border between items full width please? There's currently a margin between it and the panel.
- How about also adding the border to the first and last items?
- Please change "Tank(s)" and "Healer(s)" to either automated selection based on amount found or just always say "Tanks" and "Healers" without the parens.

**Comment by MartijnHols** [comment]
Oh just noticed something bad gotten into master so travis failing might not be for you to fix.

**Comment by kyle-glick** [comment]
@MartijnHols 
## After Recommended Changes
Note: "Tanks" and "Healers" are conditionally plural as well
image

**Comment by kfinch** [comment]
This looks really great, but one (optional) request from me is for the players to be sorted alphabetically by name within their categories.

**Comment by kyle-glick** [comment]
@kfinch 
Agreed. I hadn't notice until you pointed it out that adding the class comparison seems to have really messed up the name ordering.

**Comment by kfinch** [comment]
I don't think the ordering before this PR makes much sense either. I was considering implementing alphabetical sort when I saw this PR.

**Comment by kyle-glick** [comment]
@kfinch 

## Alphabetical-Only Ordering
image

**Comment by kfinch** [comment]
@kyle-glick Issues on master appear to be resolved, but you still need to fix compile warnings on your end in order for this to be merged:
```
./src/Main/PlayerSelectionList.js
  Line 174:  'aSpec' is assigned a value but never used  no-unused-vars
  Line 175:  'bSpec' is assigned a value but never used  no-unused-vars
```

**Pull request merged**
