### PR TITLE
[1/n] Cleanup MW shadowlands files 

### PR DESCRIPTION
**Pull request by trevorm4**
- Remove Fallen order, Faeline harmony
- Change load conditions for BDB/FLS
- Change Fort brew cd based on talents taken that reduce it

### CODE REVIEW

**Review by vohrr — COMMENTED** [review]
Faeline Harmony is a talent in the windwalker tree, do they use the file deleted here?

**Comment by trevorm4** [comment]
> Faeline Harmony is a talent in the windwalker tree, do they use the file deleted here?

It has already been moved to WW directory, so I think we're good to delete this version of the file.

image

**Review by vohrr — APPROVED** [review]

**Comment by kfinch** [comment]
I think I fucked this up while trying to fix the merge conflict ...

**Comment by kfinch** [comment]
Wait no maybe my merge was ok ? Regardless there is a build issue that needs to be looked at - missing export?

**Comment by trevorm4** [comment]
> Wait no maybe my merge was ok ? Regardless there is a build issue that needs to be looked at - missing export?

Should be good now, SaveThemAll was missing from shared index somehow.

**Pull request merged**
