### PR TITLE
Added Enchant masterful navigation

### PR DESCRIPTION
**Pull request by Gamewalker**

### CODE REVIEW

**Comment by Pewtro** [comment]
While I can somewhat imagine what this looks like, a screenshot and a log link would be appreciated

**Comment by Pewtro** [comment]
That's not what I'm seeing in quick nav at all, I've applied a small fix on my local version removing the possibility of a 5 stack, which makes it look this 
image

as opposed to 
image


What you're seeing must be some other code error, not related to how quick nav is handled.

**Comment by Pewtro** [comment]
Issue you raised is fixed in #2352

**Comment by Gamewalker** [comment]
should be obsolete with #2355

**Pull request merged**
