### PR TITLE
[Core] Weapon Oils & Sharpening Stones + Weapon Enchants

### PR DESCRIPTION
**Pull request by Sharrq**
Added Weapon Oils and Sharpening Stones to the Checklist and added Weapon Enchants to the Enchant Checker.

image

### CODE REVIEW

**Comment by Pewtro** [comment]
If you fix the conflicts this should be fine (just override the bot commit probably)

**Comment by Pewtro** [comment]
Oh - and also remember to tick away at https://github.com/WoWAnalyzer/WoWAnalyzer/issues/3664. 

I think this PR is missing these two btw - They are worse versions than the one you have implemented so maybe we should have enchanted vs best enchants here too? 
https://shadowlands.wowhead.com/spell=307719/porous-weightstone
https://shadowlands.wowhead.com/spell=307717/porous-sharpening-stone

**Comment by Sharrq** [comment]
I couldn't find those two in the blacksmithing unlearned and they weren't on the consumables vendor so I thought they got removed. I'll add them. Maybe I just missed them

**Comment by Sharrq** [comment]
So i went to add the non max Sharpening Stone/Weight stone, but from looking at Enchants .... it defines the list of "Min Enchants" but never actually uses it. 

It is just checking to see if an enchant is on there at all (i.e. if item.permanentEnchant exists/has a value). So im not sure that we need the Min item list for Enchants or Oils/Stones?? Cause Oils/Stones is doing the same thing ... if item.temporaryEnchant exists/has a value then it has something on it.

**Comment by abelito75** [comment]
Fixed the changelog for you buddy <3

**Comment by abelito75** [comment]
I might have left a hanging character in the change log : ^) but also these things

Edit: i just put a 0 in front of the 1 and now its angry. Just remove that and you gucci on the changelog... stupid linter can't you read abe

**Comment by Sharrq** [comment]
@Pewtro are these ok for me to go ahead and merge it? Not sure if my comments about the lower stones are enough to satisfy you or not

**Pull request merged**
