### PR TITLE
Refactored Convoke Spirits and added a healing attribution for Resto's version

### PR DESCRIPTION
**Pull request by kfinch**
Refactored Convoke Spirits for improved readability and also to fix some edge cases bugs, including:
* Documented everything
* Merged handling code to be more general
* Moved Convoke 'ability' object out to the main abilities file
* Fixed issue where Feral Frenzy was counted 5 times
* Fixed issue where instant spells that happen just after the Convoke buff fades were missed.
* Fixed issue where travel time casts tracking could get 'out of sync' when cast before the first Convoke

### CODE REVIEW

**Comment by rp4rk** [comment]
Can we take a look at the integration tests here

**Comment by kfinch** [comment]
> Can we take a look at the integration tests here

Yeah something weird is happening here, looking in to it.

**Comment by kfinch** [comment]
Turns out the integration test failing was an honest bug, so I fixed it

**Comment by kfinch** [comment]
image
new-convoke-tooltip

From log: https://www.warcraftlogs.com/reports/CWb8BAnMXKhrz1wd#fight=9

**Pull request merged**
