### PR TITLE
Improve tracking of cooldowns and haste for Fury (and arms)

### PR DESCRIPTION
**Pull request by oBusk**
### Description

This is a collect-up of a lot of the changes I've been working away on branches for over a year at this point 😅 I've broken off many PRs from the work, and these are some of the things that remain. I still intend to do more things for Arms/Fury warrior, but I figure 18 commits across 22 files is still a lot and I can make a PR along the way :P

- Add spells, update cooldowns (18e4e699ab311bc57e63550842d97b5c500d6f00)
- Improve Enrage for Fury
  - Normalize replacements of buffs with refresh for cleaner timelines (52fcc7a0612bfb6989adabed62eff316bc77390d 035bb8822647785ff3c616d2ed75d8667bf6b788)
  - Inform Haste tracker of increased Haste during Enrage (133ffeebeb6271a455eac2477ff2f9214af5374b)
- Improvements to timeline for Fury Warrior (7ff46abca3a86819595ac998583675721a0c9180 204bc0939bf3178657c6cd97e2b6a491de3ab15f bae719cb324ddd71b988fee799aee4af41997cf0)
- Add module to track [Hack and Slash](https://www.wowhead.com/spell=383877/hack-and-slash) resets (ff846be8e2a83a2b006d3e0178d21c8270aa4238 ff846be8e2a83a2b006d3e0178d21c8270aa4238)
- Improvements for [Champions Spear](https://www.wowhead.com/spell=376079/champions-spear) 
  - Module to track damage from Champions Spear and Champions Might (2b0bc7dcada8255b2efaa343a6172041dbc584e1)
  - Remove outdated Champions Might buff ID (26298069f1340241d77feb206d311297d1d54a94)
- Fleshed out Anger Management module that tracks resets, and shows statistics (72175a2ccbcaa1f3c0d42ded19281b53a93b597e)
- Remove outdated/unndeeded Berserkers Torment normalizer (21dc7de1837fff99b3e9415aad73734a537dba11)

Also changed maintenance status of Fury to be "basic" and added myself as the maintainer. The first "guide" page is still ancient, but feel it's fair if anyone else is curious they'd probably talk to me.

### CODE REVIEW

**Comment by oBusk** [comment]
Realized one issue for timeline, changing back to draft

**Comment by oBusk** [comment]
> Realized one issue for timeline, changing back to draft

Ah ok it's all good.

**Comment by avilene** [comment]
This removes some of the changes I had made to make Prot functional - thanks! Did you make any attempts at Hero Talents impacting CDR (like Mountain Thane's Burst of Power) or is that out of the scope of this for now.

**Comment by oBusk** [comment]
> @avilene 
> This removes some of the changes I had made to make Prot functional - thanks! Did you make any attempts at Hero Talents impacting CDR (like Mountain Thane's Burst of Power) or is that out of the scope of this for now.

Sorry did I remove something I shouldn't? 😯

No that's still some of the things that needs work 😅 I should make issues to list some of the todos...

**Comment by avilene** [comment]
> > @avilene
> > This removes some of the changes I had made to make Prot functional - thanks! Did you make any attempts at Hero Talents impacting CDR (like Mountain Thane's Burst of Power) or is that out of the scope of this for now.
> 
> Sorry did I remove something I shouldn't? 😯
> 
> No that's still some of the things that needs work 😅 I should make issues to list some of the todos...

No problem! I will finish basic Prot support but try to not touch your changes as they look good to me. I’ll do a proper review once you put it up for review

**Comment by oBusk** [comment]
@avilene Ok please let me know if I should remove any changes to the protection files! 

I created an [issue](https://github.com/WoWAnalyzer/WoWAnalyzer/issues/7065) to keep track of the things I want to do for Arms/Fury btw. There's obviously some overlap with Protection for Mountain Thane/Colossus, I'll definetely implement them in a way that should work for Prot! I'd also love to implement my improved rage tracking to Prot as well, I just need to have a look at the events for being hit. 

Also marked this story ready for review if you want to have a look :)

**Comment by emallson** [comment]
@oBusk CI fails if you use `console.error` for this. either use `this.addDebugAnnotation` to add the info to the debug ui, or switch to `console.log` / `console.warn`

**Comment by oBusk** [comment]
> @oBusk CI fails if you use `console.error` for this. either use `this.addDebugAnnotation` to add the info to the debug ui, or switch to `console.log` / `console.warn`

Looks like it was failing on the Fury example, and when I run it locally, the error i get is from DarkSigilAscension. Opened #7138 to fix that, will look at this again once that's merged

**Comment by emallson** [comment]
Still getting CI failures due to the console.error calls

**Pull request merged**
