### PR TITLE
[resto druid] More flourish enhancements

### PR DESCRIPTION
**Pull request by kfinch**
I made the Flourish changes I was talking about, most obviously I switched the main stat to 'Average HoTs Extended'.

In the table I replaced seconds extended with 'HoT Power', which I explain in the tooltip.

I also refactored the backend because it was very out of date. I updated Wild Growths to tell you about casts extended rather than individual HoTs extended, which further obviates the need to check for ToL.

I updated the tooltip a bit.

### CODE REVIEW

**Comment by kfinch** [comment]
new-flourish

**Comment by kfinch** [comment]
@buimichael needs reapproval after I fixed missing semicolon

**Comment by buimichael** [comment]
@kfinch One thing that I forgot, is the rejuvenation % SP. You need to adjust the %SP by the persistence level too.

**Comment by kfinch** [comment]
Persistence is increased duration at same HPS. The %SP constants are indications of HPS, not total healing.

**Comment by buimichael** [comment]
We may want to include this:
Incarnation: Tree of Life: Healing increased by 50%

**Comment by kfinch** [comment]
Does the rejuv bonus apply to buffs applied during the duration, or is it a dynamic buff that applies to all rejuv ticks while ToL is up?

**Comment by buimichael** [comment]
@kfinch It's 100% dynamic that applies to all rejuvs. Also in addition we could add a 15% modifier overall to all HoTs because of ToL.

**Pull request merged**
