### PR TITLE
Update to react-router-4

### PR DESCRIPTION
**Pull request by MartijnHols**
2 reasons:
- react-router's upgrade path has been shit since forever, it helps to use a recent version
- I'll probably want `react-router-redux` for the Redux branch I am working on, using the latest version makes most sense.

### CODE REVIEW

**Comment by kfinch** [comment]
Travis doesn't like something about this...

**Comment by MartijnHols** [comment]
travis is a cunt

**Comment by MartijnHols** [comment]
ohhh it's going to complain about every spec that's going to get added. that's not ideal.

**Comment by MartijnHols** [comment]
not anymore

**Comment by MartijnHols** [comment]
Well the good news is I'm probably dropping react-router entirely later

**Pull request merged**
