### PR TITLE
replace react-tooltip-lite with @radix-ui/react-tooltip

### PR DESCRIPTION
**Pull request by ToppleTheNun**
### Description

part of quest for WoWAnalyzer/WoWAnalyzer#6686

### Testing

- Test report URL: `/report/akZLCTYbN2XpQFmg/63-Mythic+Smolderon+-+Kill+(5:44)/Toppledh/standard/statistics`

Check performance boxes on standard page, check statistics, check talent statistic point counts.

### CODE REVIEW

**Comment by ToppleTheNun** [comment]
Largest bundle sizes pre-replacements:
```
dist/assets/CombatLogParser-Dyk1i-vE.js                       100.26 kB │ gzip:  24.62 kB │ map:   337.22 kB
dist/assets/CombatLogParser-B0sq48_x.js                       102.39 kB │ gzip:  23.36 kB │ map:   364.44 kB
dist/assets/CombatLogParser-CpUFv6OD.js                       104.52 kB │ gzip:  25.02 kB │ map:   371.07 kB
dist/assets/CombatLogParser-BJNUP_6g.js                       105.70 kB │ gzip:  23.97 kB │ map:   294.77 kB
dist/assets/messages-BYxAlr2s.js                              130.53 kB │ gzip:  34.98 kB │ map:     0.10 kB
dist/assets/CombatLogParser-rjCyfKT0.js                       130.78 kB │ gzip:  36.16 kB │ map:   451.39 kB
dist/assets/CombatLogParser-kNvXCWyM.js                       132.04 kB │ gzip:  45.19 kB │ map:   411.76 kB
dist/assets/messages-BC98uplr.js                              133.14 kB │ gzip:  33.11 kB │ map:     0.10 kB
dist/assets/messages-C2nzMy2Z.js                              133.14 kB │ gzip:  33.11 kB │ map:     0.10 kB
dist/assets/messages-BVjcz2lZ.js                              133.14 kB │ gzip:  33.11 kB │ map:     0.10 kB
dist/assets/messages-D4YNxgod.js                              133.14 kB │ gzip:  33.11 kB │ map:     0.10 kB
dist/assets/messages-BopSV_lL.js                              133.14 kB │ gzip:  33.11 kB │ map:     0.10 kB
dist/assets/messages-Ogy2PKj9.js                              133.94 kB │ gzip:  34.17 kB │ map:     0.10 kB
dist/assets/messages-BhaZLEwx.js                              134.18 kB │ gzip:  34.07 kB │ map:     0.10 kB
dist/assets/CombatLogParser-CD1R9-fx.js                       134.86 kB │ gzip:  30.15 kB │ map:   451.99 kB
dist/assets/messages-DaDHhD9I.js                              135.98 kB │ gzip:  41.04 kB │ map:     0.10 kB
dist/assets/CombatLogParser-DtEsL999.js                       136.25 kB │ gzip:  30.81 kB │ map:   478.51 kB
dist/assets/messages-DlJb3gCs.js                              137.87 kB │ gzip:  35.80 kB │ map:     0.10 kB
dist/assets/CombatLogParser-CrPIp8Du.js                       138.48 kB │ gzip:  27.74 kB │ map:   458.14 kB
dist/assets/CombatLogParser-mXnQgO1F.js                       140.19 kB │ gzip:  28.22 kB │ map:   488.26 kB
dist/assets/CombatLogParser-CC1mY90_.js                       270.27 kB │ gzip:  56.37 kB │ map:   851.34 kB
dist/assets/CombatLogParser-DOmg2HK6.js                     1,097.01 kB │ gzip: 358.55 kB │ map: 4,839.01 kB
dist/assets/index-JkGkdR3X.js                               2,153.50 kB │ gzip: 694.73 kB │ map: 6,608.52 kB
```

Largest bundle sizes post-replacements:
```
dist/assets/CombatLogParser-ZHlZza-8.js                       100.25 kB │ gzip:  24.62 kB │ map:   337.18 kB
dist/assets/CombatLogParser-Cj2VWQhs.js                       102.38 kB │ gzip:  23.36 kB │ map:   364.43 kB
dist/assets/CombatLogParser-MorvcvQA.js                       104.51 kB │ gzip:  25.02 kB │ map:   371.02 kB
dist/assets/CombatLogParser-Cru1u6sb.js                       105.70 kB │ gzip:  23.97 kB │ map:   294.77 kB
dist/assets/messages-BYxAlr2s.js                              130.53 kB │ gzip:  34.98 kB │ map:     0.10 kB
dist/assets/CombatLogParser-GUNab-hQ.js                       130.73 kB │ gzip:  36.15 kB │ map:   451.24 kB
dist/assets/CombatLogParser-94NklWUP.js                       132.04 kB │ gzip:  45.20 kB │ map:   411.76 kB
dist/assets/messages-BC98uplr.js                              133.14 kB │ gzip:  33.11 kB │ map:     0.10 kB
dist/assets/messages-C2nzMy2Z.js                              133.14 kB │ gzip:  33.11 kB │ map:     0.10 kB
dist/assets/messages-BVjcz2lZ.js                              133.14 kB │ gzip:  33.11 kB │ map:     0.10 kB
dist/assets/messages-D4YNxgod.js                              133.14 kB │ gzip:  33.11 kB │ map:     0.10 kB
dist/assets/messages-BopSV_lL.js                              133.14 kB │ gzip:  33.11 kB │ map:     0.10 kB
dist/assets/messages-Ogy2PKj9.js                              133.94 kB │ gzip:  34.17 kB │ map:     0.10 kB
dist/assets/messages-BhaZLEwx.js                              134.18 kB │ gzip:  34.07 kB │ map:     0.10 kB
dist/assets/CombatLogParser-C3KB6YOX.js                       134.86 kB │ gzip:  30.16 kB │ map:   451.99 kB
dist/assets/messages-DaDHhD9I.js                              135.98 kB │ gzip:  41.04 kB │ map:     0.10 kB
dist/assets/CombatLogParser-B83bnsud.js                       136.20 kB │ gzip:  30.80 kB │ map:   478.38 kB
dist/assets/messages-DlJb3gCs.js                              137.87 kB │ gzip:  35.80 kB │ map:     0.10 kB
dist/assets/CombatLogParser-CqdznlIL.js                       138.24 kB │ gzip:  27.73 kB │ map:   457.71 kB
dist/assets/CombatLogParser-CQBAaELU.js                       140.19 kB │ gzip:  28.23 kB │ map:   488.26 kB
dist/assets/CombatLogParser-BCjoULv8.js                       270.22 kB │ gzip:  56.35 kB │ map:   851.23 kB
dist/assets/CombatLogParser-BmZStwIA.js                     1,097.00 kB │ gzip: 358.54 kB │ map: 4,839.00 kB
dist/assets/index--BqX_Vi_.js                               2,182.72 kB │ gzip: 706.40 kB │ map: 6,772.34 kB
```

Looks to be a bundle size gain of roughly 19kb.

**Review by emallson — COMMENTED** [review]
going to pull this locally tonight and play around.

dumping some notes:

- [x] check whether `hoverable` is now default or if all hoverable tooltips became non-hoverable
- [x] ~~sanity check CSS~~ actually its a module so it should be very hard to break something else :thinking: unless something else used the old css

**Review by emallson — COMMENTED** [review]
okay, everything works. everything is hoverable by default now, which i think is fine. however: the tooltip delay by default is *really long*

IMO we should reduce the default duration of [700ms](https://www.radix-ui.com/primitives/docs/components/tooltip#provider) to something like 200-250ms at least.

other than that, :+1:

**Comment by ToppleTheNun** [comment]
I've noticed a couple of pieces of weird behavior as I've been testing this with different delays:
uhhhhhhhhhh

This is only an issue for components that have tooltips that will be hit very close together (i.e., performance boxes and debug annotations).

I've yet to find a good way to fix this, which might push me back towards updating react-tooltip-lite to work with React 18 instead of using this.

**Comment by ToppleTheNun** [comment]
Alright, so found a fix for the above thing. Setting `disableHoverableContent` to `true` makes the tooltips snappy because it no longer has to do a grace check for the hovered part of the tooltip: https://github.com/radix-ui/primitives/issues/2592

**Pull request closed without merging**
