### PR TITLE
[core] Fixed the green on the ABCHealing bar to be the same as the Healing Done green

### PR DESCRIPTION
**Pull request by kfinch**

### CODE REVIEW

**Comment by MartijnHols** [comment]
They're different things, so maybe they should have different colors 🤔 I left it as it is as I couldn't decide a good approach. Maybe regular active time should be yellow or something?

**Comment by kfinch** [comment]
I've got an idea, will implement when home.

**Comment by kfinch** [comment]
Ok I tried yellow and it looked terrible. Best I could come up with is blue/purple/red. Please don't leave it as that green slightly off from the other green, it's triggering me.

**Comment by kfinch** [comment]
healingabc-2

**Comment by kfinch** [comment]
@MartijnHols how do you feel about the above colors?

**Comment by MartijnHols** [comment]
I think it needs further experimentation 😅

**Comment by MartijnHols** [comment]
I guess we can merge this with both bars the same green 🤷‍♂️

**Comment by kfinch** [comment]
Man, the blue/purple/red kinda kinda grew on me. What about green/purple/red?

**Comment by kfinch** [comment]
Fine fine, I've gone back to just changing the green. You should consider the blue/purple/red tho, it's rad.

**Comment by MartijnHols** [comment]
I guess I'll merge, but the different greens never bothered me 😅

**Pull request merged**
