### PR TITLE
[NEXT] Styling idea for the scrollbar on the timeline

### PR DESCRIPTION
**Pull request by Alastair-Scott**
Was just an idea I had to make the scroll bar look a little more fancy. 

Current:
image

Idea:
image

### CODE REVIEW

**Comment by Dambroda** [comment]
I like the idea of reskinning it for sure, but am not really a fan of how this looks. I think keeping everything solid is the way to go, rather than this glow/whatever you want to call it 

That's my opinion ofc, so looking to see what others say :)

**Comment by Alastair-Scott** [comment]
Just having the borders coloured does make it match the icons fairly well and so on the full page it looks better. I do think I should remove the box shadows and just have it as solid colours though

**Comment by Dambroda** [comment]
Yeah its just the glow I'm personally not a fan of

**Comment by Alastair-Scott** [comment]
Scrollbar with no box shadow
image

**Comment by sMteX** [comment]
How about filling it with the color (like the bars for GCD in the timeline)? I think that would fit more for the overall theme we're on.

**Comment by Alastair-Scott** [comment]
With solid colours:
image

**Pull request merged**
