### PR TITLE
re-enable Beast Mastery log parser

### PR DESCRIPTION
**Pull request by ToppleTheNun**

### CODE REVIEW

**Review by emallson — APPROVED** [review]
assuming you tested and it works. if so, ship it

**Comment by ToppleTheNun** [comment]
This was mostly to fix an issue where Beast Mastery Hunters were still clickable on the player selection screen, but would load forever when clicked.

**Comment by Pewtro** [comment]
SV is the same I think 😢

**Comment by ToppleTheNun** [comment]
I'll do the same thing for Survival as well, just going to go find a log.

**Pull request merged**
