### PR TITLE
[HPriest] Mana Usage Chart

### PR DESCRIPTION
**Pull request by TJMoats**
I refactored the druid mana tracker to be usable by other classes. I made the priest version an expandable statistic box as it's a bit big otherwise.

What it looks like: https://i.imgur.com/FK0o802.png

I'd like to abstract one more level out and have a generic "Pie Chart" card, but I will save that for another PR.

### CODE REVIEW

**Comment by Pewtro** [comment]
This doesn't seem useful information. There are too many bars to properly digest the information

**Comment by TJMoats** [comment]
Are there other classes that have a mana usage tab that I can borrow from?

**Comment by Pewtro** [comment]
Havoc DH has a fury usage tab you can look into, that's one I know for sure exists

**Comment by TJMoats** [comment]
I'll emulate that style of resource tracking. Thanks!

**Pull request closed without merging**
