### PR TITLE
[UI] Make tab menu items horizontal

### PR DESCRIPTION
**Pull request by avilene**
As suggested in #398 I've made the tab menu items horizontal. 

image

### CODE REVIEW

**Comment by MartijnHols** [comment]
Hey thanks for tackling another issue! This is a good start, but I think it needs a few more changes before it's ready. The goal I had envisioned was to make it similar to the devtools tabs;

image

Another inspiration could be GitHub's tabs;
image
image

The gist of it is that the headers MENU and SUGGESTIONS can be removed with such a layout as the tab selection itself and the highlighting of the active menu item should suffice. This would save also save some vertical space from your current proposed solution. The difficulty in doing this would be in giving the minor importance toggle a good looking spot, and making the tabs fit neatly within the layout is probably also non trivial.

There are several solutions for fixing the mobile layout, a simple and temporary one would be to set the tab items to not wrap (white-space: nowrap), better might be similar to the devtools; horizontal scrolling, or perhaps a `...` button like I've seen in other layouts.

**Comment by fyruna** [comment]
Okay! I can poke in the css files as well, right?

**Comment by MartijnHols** [comment]
Yes

**Comment by fyruna** [comment]
This is what I've made it into, suggestions are welcome.
image
image

**Comment by Pewtro** [comment]
The blue outline in the top most picture when it's selected looks out of place

**Comment by fyruna** [comment]
@Pewtro Good find, removed it. Also added a hover state on the non-selected tabs
image

**Comment by MartijnHols** [comment]
I think we should use something other than orange as the active state. Our color scheme doesn't really include orange. I realize the current active state of the menu items is too hard to see, so maybe you can play around with the red border?

**Comment by fyruna** [comment]
image
How about this, and perhaps making the text bold when its selected so its even more clear?

**Comment by MartijnHols** [comment]
Looks good! Unsure about making the text bold, it might also make the tabs jump a bit, but feel free to give it a try.

**Comment by fyruna** [comment]
Nah I'll leave it as is, bold might just be a tad overdone.

**Review by MartijnHols — APPROVED** [review]
Thanks!

**Pull request merged**
