### PR TITLE
[Resto druid] Removed healer stat weights

### PR DESCRIPTION
**Pull request by abelito75**
Removing healer stat weights in favor of QElive

### CODE REVIEW

**Comment by emallson** [comment]
doesn't even build smdh @abelito75

**Comment by abelito75** [comment]
> doesn't even build smdh @abelito75

I know. I was doing this when work called... Also one random generic conduit is made druid specific zzz

**Comment by emallson** [comment]
ngl unless that conduit actually changes gameplay you can just remove it as well

**Comment by abelito75** [comment]
I talked to voulk. He said keep so I keep
Also I did another PR for this and it's already in

**Comment by emallson** [comment]
Fair enough

**Pull request closed without merging**
