### PR TITLE
add functions for T29 tier sets

### PR DESCRIPTION
**Pull request by ToppleTheNun**
From my testing, this looks like it might need some support on the WCL side. Below is a snippet of a tier piece from T28 logs and a snippet of a tier piece from T29 logs.

**T28**
```json
{
  "id": 188892,
  "quality": 4,
  "icon": "inv_leather_raiddemonhunterprogenitor_d_01_helm.jpg",
  "itemLevel": 298,
  "bonusIDs": [6652, 7578, 7359, 8765, 8151, 8256, 1518, 6646],
  "setID": 1501
}
```

**T29**
```json
{
  "id": 200345,
  "quality": 4,
  "icon": "inv_helm_leather_raiddemonhunterprimalist_d_01.jpg",
  "itemLevel": 401,
  "bonusIDs": [1463, 8767]
}
```

### CODE REVIEW

**Comment by Pewtro** [comment]
I think you swapped your T28 and T29 around

**Comment by ToppleTheNun** [comment]
> I think you swapped your T28 and T29 around

I did, my apologies. It's now fixed.

**Comment by Pewtro** [comment]
LGTM though, WCL probably needs to export these values again but I assume this is the way they'll want to do it again

**Comment by emallson** [comment]
The `setID` *should* "just work" once we import dragonflight data at prepatch release, but if not I'll make it work :)

**Review by emallson — APPROVED** [review]

**Pull request merged**
