### PR TITLE
Show DH Fury usage

### PR DESCRIPTION
**Pull request by viridis**
screen shot 2018-10-01 at 15 51 40

On par with: https://github.com/WoWAnalyzer/WoWAnalyzer/blob/master/src/parser/hunter/shared/modules/features/FocusUsage.js

### CODE REVIEW

**Comment by joshinat0r** [comment]
Sooooo, your PR adds basically whats in the fury usage tab? 🤔 

image

**Comment by viridis** [comment]
Yeah I guess. I just really liked it for Focus on Hunters and just wanted to add it for consistency. It felt easier to grasp the relations between skills in a donut chart. Can close.

**Comment by yajinni** [comment]
Personally i dont mind it. Gives you an at a glance view. If you want more details go to the tab. If it makes things look messy they yeah get rid of it. But is it that bad of a thing?

**Comment by joshinat0r** [comment]
Whats the consensus on this one now? The discussion on discord showed that the majority doesn't like the duplication of the resource-tracker (or don't like doughnut charts).

**Comment by TJMoats** [comment]
I had a similar pr here: https://github.com/WoWAnalyzer/WoWAnalyzer/pull/2345

Mine was far too verbose to be featured as a card, but I think the preferred method is keeping resource breakdowns in the tab view.

**Comment by yajinni** [comment]
Well the resource tab doesnt show % So you cant at a glance get an idea for your ratios.  
That being said i am not 100% sure how useful seeing those ratios at a glance would be tbh.
Maybe just add % to the resource tab at this point?

**Comment by joshinat0r** [comment]
The percentage is hidden in the tooltip already.

**Comment by emallson** [comment]
@joshinat0r final verdict?

**Comment by joshinat0r** [comment]
Still not quite sure, I think the overall feedback on discord was against it (or doesn't like doughnuts), so I'm going to close this one.
@viridis but feel free to reopen this one if you feel like its crucial for DH and convince a few people on discord 😄

**Pull request closed without merging**
