### PR TITLE
[frost mage] Winter's Chill render fix and Brain Freeze appearance update

### PR DESCRIPTION
**Pull request by kfinch**
Winter's chill display could split strangely on wider windows, this fixes the issue.

Before:
winters-chill-before

After:
winters-chill-after

### CODE REVIEW

**Comment by kfinch** [comment]
Woops I intended to put second commit on different PR, but these are similar enough so whatever.... this second commit is updates to the BrainFreeze module to make it display in same style as Winter's Chill. Detection for expired procs was added, suggestion / stat reworded a bit.

brain-freeze

**Comment by MartijnHols** [comment]
Please solve the merge conflicts so this can be merged.

**Comment by kfinch** [comment]
I tried to do it in browser because it's a simple conflict, not sure that I did it right though...

**Comment by kfinch** [comment]
I'm pretty sure that merge did resolve the conflict and just didn't show right... in any case I pushed another commit to clear things.

This commit added my name to Frost Mage maintainer, after Sharrq. While developing this spec with Sharrq we discussed if my name should be on maintainer, and decided "not until I've actually contributed several modules". At this point I think I have contributed several modules.

**Pull request merged**
