### PR TITLE
[Hunter] Tier 29 BM tier, general housekeeping and bugfixes

### PR DESCRIPTION
**Pull request by Pewtro**
### Description

Adds support for T29 sets for Beast Mastery
Fixes a few bugs around modules
Using ts-prune found all unused exports in retail hunter folders and cleaned them up.

### CODE REVIEW

**Comment by emallson** [comment]
i am gonna need to try this `ts-prune` thing :eyes:

**Comment by Pewtro** [comment]
It's very neat! 

Quick and dirty get a list of unused for a class/spec on linux/macos: 
`npx ts-prune | grep **/retail/monk`

On windows, I don't have a good equivalent, but I think it should be doable using findstr somehow

**Comment by ToppleTheNun** [comment]
iirc it's technically built into the TypeScript server as well. You can setup VS Code to do it automatically: https://www.techiediaries.com/vscode-automatically-organize-typescript-imports/

WebStorm can do it as well.

**Comment by Pewtro** [comment]
That doesn't look like what ts-prune does

**Comment by ToppleTheNun** [comment]
I think I misread "exports" as "imports"

**Comment by B0uss** [comment]
> It's very neat!
> 
> Quick and dirty get a list of unused for a class/spec on linux/macos: `npx ts-prune | grep **/retail/monk`
> 
> On windows, I don't have a good equivalent, but I think it should be doable using findstr somehow

Hi @Pewtro, on windows, I think we could use `npx ts-prune | select-string "retail\\monk"`

**Review by emallson — APPROVED** [review]

**Pull request merged**
