### PR TITLE
[Core] Non timebased buff tracker

### PR DESCRIPTION
**Pull request by abelito75**

### CODE REVIEW

**Comment by emallson** [comment]
This looks sane to me. Not convinced we should merge w/o first actually using it in an analyzer to make sure it doesn't come with problems/quirks of its own

**Comment by abelito75** [comment]
I made it without attaching anything to it so it wouldn't be bogged down or held up by any analyzer slog.
I can totally tie it to one real quick if desired... 
I might also expand on this a bit to make it so toy with buffs from different combatants n what not tracked too

**Comment by emallson** [comment]
my concern is that we try to use this and then realize that we're just trading one ordering issue for another

**Comment by emallson** [comment]
Thinking about it, having the ability to choose your trade-offs is probably fine but i do want this to be used somewhere before it is merged so that we don't end up with (another) analysis tool that just rots in the codebase

**Comment by emallson** [comment]
Closing for now until we find a place to use it. Keep it in your back pocket @abelito75

**Pull request closed without merging**
