### PR TITLE
Atonement ID Fix

### PR DESCRIPTION
**Pull request by rp4rk**
Previously the two atonement IDs included in `SPELLS_PRIEST.js` were the atonement cast instance for non-crits only, and the buff instance. This PR contains a fix that differentiates between the buff instance, and the crit and non-crit cast instances.

### CODE REVIEW

**Comment by MartijnHols** [comment]
Could you explain in more detail what the differences are? One is a buff, the other only a heal?

**Comment by rp4rk** [comment]
Sure thing, the two instances of atonement you find while parsing casts are simply to designate crit and non-crit atonements:
[Non-crit](http://www.wowdb.com/spells/81751-atonement)
[Crit](http://www.wowdb.com/spells/94472-atonement)

Notice that the first has a flag that says it can never critically strike, if you do a filter on WCL for this id, it verifies that this is the case.

http://www.wowdb.com/spells/194384-atonement

This is the buff ID that will be applied and removed from players if they have Atonement, and is completely separate from the cast IDs.

I hope this clarifies things!

**Comment by MartijnHols** [comment]
`crit and non-crit atonements` atonement heal events I guess? If so please rename them to `ATONEMNET_HEAL_NON_CRIT` and `ATONEMENT_HEAL_CRIT`. That should clear it up completely.

**Comment by MartijnHols** [comment]
Nice, thanks for taking the time to figure this one out!

**Pull request merged**
