### PR TITLE
Verify patch 9.1.5 compatibility and bump support

### PR DESCRIPTION
**Pull request by darkpsy3934**
After looking at patch notes and confirming no changes have been done since 9.0.5, I have determined the analysis is correct for 9.1.5.  Bumped patch support to 9.1.5, added to CONTRIBUTORS, and added changelog entry.

### CODE REVIEW

**Comment by abelito75** [comment]
Are we sure rotation/covenant choices haven't changed over that time frame?

**Comment by darkpsy3934** [comment]
To my knowledge, they have remained the same.

**Comment by HawkCorrigan** [comment]
You're gonna need to import your "name" in the changelog as well.

**Review by emallson — APPROVED** [review]
AFAIK from people in guild the only real change from 9.1.5 is the ability to play other covenants where it makes sense, so this seems fine.

**Pull request merged**
