### PR TITLE
guardian deathlog

### PR DESCRIPTION
**Pull request by yajinni**

### CODE REVIEW

**Comment by Gebuz** [comment]
I made it ignore abilities categorized as DEFENSIVE on the "Personals Available" in #1715

**Comment by Gebuz** [comment]
@yajinni Remember Rage of the Sleeper! Otherwise good to merge.

**Comment by joshinat0r** [comment]
Yeah, adding those "rotational" defensives to the cooldown list wasn't inteded (thought the "defensive" category was just used for cooldowns, not rotational defensives). I think I would have added IF in that case to the defensive_buffs-file.
Will add a check for spells that have no cooldown and hide them in the "cooldowns available" column.

**Comment by yajinni** [comment]
I mean something like iron fur. If you die and you dont have it up you screwed up though. So shouldnt that be showing? Or are you guys talking about something else.

**Comment by joshinat0r** [comment]
It wasn't about if it should be displayed as a buff, totally should. But giving it the defensive-category would add it to the "cooldown available"-tab, which should not happen (its less of a cooldown, more a thing you maintain). Gebuz merged already a fix for that.

**Pull request merged**
