### PR TITLE
Rolled Balance DoT uptimes into one graph and added notional damage to Convoke the Spirits statistic

### PR DESCRIPTION
**Pull request by kfinch**
This is basically a copy/paste of work I did for Feral several months ago, but I think it adds to the experience.

image

### CODE REVIEW

**Comment by abelito75** [comment]
Love the look of this. I might steal it later

**Comment by kfinch** [comment]
Found some more code merging I can do between the ConvokeSpirits modules so also gonna add that to this PR (and also fix the integration test)

@abelito75 the code for making one of these stat boxes is in general and meant to be used in many places, so feel free

**Comment by kfinch** [comment]
My damage tallying code was basically copied from Balance / Feral / Guardian versions of the module, so I unified them in the base module to avoid all the duplicated code.

Also made all the display modules wide for Convoke so that the dropdown is less cramped
image

**Comment by kfinch** [comment]
Everything is in now, ready for merge

**Pull request merged**
