### PR TITLE
Added a changelog tab which should be more visible than the spec information overlay

### PR DESCRIPTION
**Pull request by MartijnHols**
image

### CODE REVIEW

**Comment by MartijnHols** [comment]
Updated to include changelog definition and rendering changes;
image

**Comment by MartijnHols** [comment]
Now shows amount of recent changes (in the past week).

image

**Comment by fasib** [comment]
Shouldn't the date `5-11-2017` be rendered as `05-11-2017`, like in the first screenshot?

**Comment by MartijnHols** [comment]
Date format depends on browser settings.

**Comment by MartijnHols** [comment]
Full backwards compatibility (string based is deprecated though).

**Pull request merged**
