### PR TITLE
[Restoration Shaman] Healing Rain tick calculation change

### PR DESCRIPTION
**Pull request by niseko**
Currently the healing rain module divides ticks by looking at the exact millisecond, but looking at logs it appears that ticks can be split up a bit (seen up to 83ms). Often you have 1 hit followed by 5 hits within 5ms, which it currently interprets as 2 different sets of ticks even though its just 1.
I gave it a buffer of 85ms to correct that behaviour, and average ticks went up in all logs as you'd expect, and checking the array i haven't found wrong groupings.

Varimathras rank 1 log where you'd expect 6 hits per tick (before & after):
imageimage
Argus (again you'd expect high amount of hits):
imageimage
Kingaroth:
imageimage

### CODE REVIEW

**Comment by MartijnHols** [comment]
Modules like this and behavior like that could really benefit from some tests. Would you be willing to add a set for this PR?

**Comment by niseko** [comment]
Seems like its time to learn how tests work, I'll read up and try it out.

**Comment by niseko** [comment]
I added some kind of test, feedback would be appreciated since I've never done something like that

**Comment by MartijnHols** [comment]
Looks good. I recommend trying to test all requirements so that all code paths are hit, in particular the change in this PR.

**Pull request merged**
