### PR TITLE
Resto druid flourish display changes

### PR DESCRIPTION
**Pull request by buimichael**
[Screenshot from Gyazo](https://gyazo.com/41713a2a4d8164bd51b6c7bce5e5fa74)

### CODE REVIEW

**Comment by kfinch** [comment]
Oh I am too late... I really hate 'average seconds extended' as a Flourish metric, because it's a really bad one. Breaking it down by cast doesn't make it any better. Also, it seems silly to show both Duration and # of HoTs, because the former will always be 6 times the latter. We should find a way to do throughput of extended HoTs sooner rather than later.

**Comment by buimichael** [comment]
@kfinch 
I'd have to disagree that checking the amount of HoTs being extended as a bad metric. 
By breaking it down by cast we can see where we could have utilized a better flourish.
Also I don't see a problem with showing the same data in two different formats (same as we show healing done by number and by a bar atm)

I agree that HPS contribution should be used instead of average seconds in the main display. Flourish in a sense is very similar to Evangelism and tbh, what we want is probably exactly what the Evanglism box is showing:
 [Screenshot from Gyazo](https://gyazo.com/d3d0c8191ca6761c65a0be9817a5a97c)

Although tracking the healing contribution of each flourish may be complex to implement, especially accounting WG healing and rejuv healing. But it sure is possible.

**Comment by kfinch** [comment]
There is one very important difference between Evangelism and Flourish, and that's that all Atonements are created equal but all HoTs are not. The healing done by 6 seconds of Cenarion Ward is much higher than that of 6 seconds of Wild Growth is much higher than 6 seconds of Cultivation / Germination / Rejuvenation is much higher than 6 seconds of Spring Blossoms / Regrowth.

**Comment by buimichael** [comment]
Yeah I agree with that, we should probably show the duration/count of each HoT instead of treating them as equal.

**Pull request merged**
