### PR TITLE
 Allow castEfficiency to be null in ArcaneTorrent 

### PR DESCRIPTION
**Pull request by Salmonhands**
This appears to be the intended functionality based on the fact that this.castEfficiency is later compared to null. 

Might be cleaner to just add support for a 0 casting efficiency if you want me to do that instead.

### CODE REVIEW

**Comment by MartijnHols** [comment]
Also please consider adding a changelog entry

**Review by Pewtro — CHANGES_REQUESTED** [review]
With a review already existing, marking this as changes requested. 
- also has a merge conflict to fix.

**Comment by Pewtro** [comment]
Over a month with no updates on this. Closing it for now, if you wish to make the requested updates, you can always just reopen this or a new PR with the updates.

**Comment by MartijnHols** [comment]
Actually it looks like the original file was already changed and does what this PR suggested, so closing since it was already solved.

Thanks for the PR.

**Pull request closed without merging**
