### PR TITLE
[General] Add extract_spell.js script for gathering spell data for raids

### PR DESCRIPTION
**Pull request by hpabst**
**Context:**
 I'm looking at getting back into WowAnalyzer development and specifically supporting the CoreMitigationCheck.js feature going forward in SL. CoreMitigationCheck.js requires spell data from WowHead for each boss fight where the feature is supported, which back in Legion when I introduced it was manually gathered and aggregated in src/common/spells/encounter.js. This was a very tedious task taking several hours each raid tier so this script should automate gathering that data going forward. This is also my first time performing web scraping or using Selenium, and I haven't touched JS in about 2 years so tear this apart at will.

**New Dependencies:**
- Add dev dependencies on chromedriver and selenium-webdriver to support script.

**Testing:**
- Manual sampling and verification of script output against Castle Nathria, Nya'lotha, and Eternal Palace data on WowHead. Script gathered all sampled data correctly.

### CODE REVIEW

**Comment by emallson** [comment]
hey, so i have some bad news: this feature went (basically) unused for the entirety of BFA because they just stopped giving us physical tankbusters. We had Fetid, Grong, and then we had Shad'har and aside from that they basically didn't exist.

I haven't done a deep dive on next tier yet, but an early look was similar. As a result, I've actually been contemplating removing the feature entirely until such a time as they actually put tankbusters back in the game.

On an entirely different note: I don't think I'm comfortable with us scraping Wowhead when we really only a couple of abilities. Seems like a lot to add a brittle script (it will break if they change the formatting) and a large dependency for that.

**Comment by hpabst** [comment]
@emallson 

Well then. Uuuuuh, at least I learned something about Selenium and got back on the JS horse a bit? I'll close and discard for now.

**Comment by emallson** [comment]
Yea, sorry to be the bearer of bad news. :/ at least selenium is a useful tool that now you have some experience with

**Comment by hpabst** [comment]
Hey, I should've reached out before starting on it to make sure this script would even work.  :P
I'll start looking into other prot paladin/general tank related issues if it's alright with you.

**Comment by emallson** [comment]
I don't have issues posted for prot paladin at the moment. If you want to talk on discord we can coordinate that though. I started on prot paladin updates (see #3859), but there is more work to be done.

**Comment by hpabst** [comment]
That'd be great. I'll reach out once I begin refamiliarizing myself with the project.

**Pull request closed without merging**
