### PR TITLE
[Marksmanship] fixes a owl trinket crash

### PR DESCRIPTION
**Pull request by Pewtro**
Something introduced a crash I haven't had anywhere before - this fixes  it, noticed it in one of my own logs... 

https://wowanalyzer.com/report/BVGYDTWv2wfAbdQF/49-Heroic+Argus+the+Unmaker+-+Kill+(9:11)/Putro

### CODE REVIEW

**Comment by kfinch** [comment]
Oh, this is my fault, I refactored a bunch of the trinket modules, and the PR for that got merged a couple hours ago. I did not notice that there was a special extension for this trinket, and clearly I renamed something that broke yours.

**Comment by Pewtro** [comment]
I can change mine into an array aswell I guess?

**Comment by kfinch** [comment]
Yes that's the preferred solution

**Comment by Pewtro** [comment]
There we go, it pulls from main modules array again now

**Comment by Pewtro** [comment]
No problem 😄 Got spooked it was on my end somewhere

**Pull request merged**
