### PR TITLE
Resto druid - updated mana used chart with hpm

### PR DESCRIPTION
**Pull request by buimichael**
img

/report/7Pp8rQgCJmbTtFDz/71-Mythic+Fetid+Devourer+-+Wipe+16+(5:35)/4-Blazyb

Requesting help with the presenting this data so it's more intuitive, if possible. Possibly have a header with 
Ability, Mana usage, HPM with tooltips on what they mean.

### CODE REVIEW

**Comment by MartijnHols** [comment]
I don't think you should add this to the mana usage panel as it makes it more confusing what it shows. How about duplicating it and showing a separate panel? Or alternatively add a toggle to switch between *Mana usage* and *Mana effectiveness* or something like that so both views are pure.

**Comment by MartijnHols** [comment]
Also isn't @joshinat0r working on a HPM tab too?

**Comment by buimichael** [comment]
@MartijnHols Hey, as suggested I've broken the HPM module as it's own. Whenever @joshinat0r finishes with his implementation of a generic HPM module we can look into merging/refactoring the code. I'd like to get this module out to the public.

img

**Comment by MartijnHols** [comment]
There are some conflicts ([sorry](https://media.giphy.com/media/K1QnLV1caRpuw/giphy.gif)!), please merge from master.

**Comment by buimichael** [comment]
Thanks for the review, i'll look into the change requests whenever I have some time over.

**Comment by buimichael** [comment]
Retracting this PR until further. PR #2417 seem to solve similar. I'll have to look into incorporating that module instead.

**Pull request closed without merging**
