### PR TITLE
Death Knight - Unholy - Create T20_2pc.js

### PR DESCRIPTION
**Pull request by Maxweii**
Creating tracker for tier 20 four piece buff uptime

### CODE REVIEW

**Comment by Maxweii** [comment]
Hm I think I meant 2 piece then, I mix them up a lot, and that was next part was currently on. Though Keira or Khaz might get that done faster than I would

**Comment by Maxweii** [comment]
Should be fixed now and pushed a thing for adding the tier set bonus for Unholy - ah as I type this fixing a wording on things so it matches

**Comment by Pewtro** [comment]
To correctly monitor uptime you will need to track this: http://www.wowhead.com/spell=246995/master-of-ghouls

The buff you currently track is merely the hidden buff granted when tier202p is equipped and should be used in on_initialized() and anywhere else you need the icon, but is not the one you want to track the uptime of.

**Comment by Pewtro** [comment]
Adding to my original request: Please ensure that both ``UNHOLY_DEATH_KNIGHT_T20_2SET_BONUS_BUFF`` and ``UNHOLY_DEATH_KNIGHT_T20_2SET_BONUS`` exist in SPELLS (right now only 1 does)

**Comment by Maxweii** [comment]
Talked to Khazzak and he's going to finish this up/fix things for it.

**Pull request closed without merging**
