### PR TITLE
Add a 1 second window for prepots

### PR DESCRIPTION
**Pull request by avilene**
Could be useful due to Aggramar (or other bosses) being slow at putting players in combat. #1218

### CODE REVIEW

**Review by Gebuz — CHANGES_REQUESTED** [review]
There needs to be a check in `on_byPlayer_cast` if the timestamp is less than `maxPrepotWindow` to ensure that a pot isn't counted as both a prepot and second pot.

In the case of a messed up prepot resulting in the player only being able to use one pot, should we display it as missing a prepot or missing a second pot? I'm not sure what's better. Either way it's probably safe to be pretty generous with the buffer window to ensure it catches all potential prepots (I'm not sure how long you actually have on aggramar).

**Comment by MartijnHols** [comment]
I don't think we should increase the buffer time as my experience is that I immediately get in combat when someone else pulls (damn people landing hits on the boss at 1 or 2 seconds before end of countdown).

**Comment by Gebuz** [comment]
couldn't we just assume that it is always a normal pot until a second one is used? I suppose deaths and potting again would mess with that though.

**Comment by MartijnHols** [comment]
Some fights like Gul'dan offer combat resets at important moments. I think we should support that properly as well. A 1 second buffer could be solve the issue, but maybe 500ms would too (looking at the issue report it would).

**Comment by MartijnHols** [comment]
Since this PR has been stale for over a month I'll close it. Please make a new PR if anyone wishes to continue work on this.

**Pull request closed without merging**
