### PR TITLE
[Hunter] Talent for all 3 specs and spell/buff data for BM and MM

### PR DESCRIPTION
**Pull request by Pewtro**
Initial work on getting modules ready. 

Need to sit down and retrieve spell/buff data for Survival, then module cleanup can properly start.

### CODE REVIEW

**Comment by Pewtro** [comment]
Stop lying Travis 😠 It's fine on my end 👿

**Comment by MartijnHols** [comment]
I'm afraid if Travis is complaining about that there's an issue somewhere in your code. Did you check the line in the Haste module that the log shows?

**Comment by Pewtro** [comment]
Can't skimp on nuking everything I guess - will probably just disable large portions before I figure out what can be repurposed etc.

**Comment by Pewtro** [comment]
Now I'm truly at a loss... 😓 
image

**Pull request merged**
