### PR TITLE
DF Re-org

### PR DESCRIPTION
**Pull request by emallson**
This incorporates all the changes from @Pewtro's PR, plus a reorganization back into a mono-package (see #5049). I haven't fully tested that this resolves the issues with auto-imports (see #4905) but will before merging.

In the process of doing this, I discovered that no tests were running in the `analysis` folder *except* for integration tests. This is now fixed.

As part of prep for DF, there are several additional TEMPORARY changes:

- All integration test files have been removed. New integration tests will need to be set up for supported specs.
- All broken tests have been annotated with `.skip` (+ other changes needed to satisfy the linter/tsc). These will need to be re-enabled later. most of the tests that have broken are broken due to talent changes.
- All retail specs have been fully disabled. This means that TypeScript will not load or parse the files, they will not appear on the site in dev or production mode, etc. In order to re-enable a spec, uncomment its import and export in `src/parser/index.ts`.
  - This required setting the analysis folder to be excluded in `tsconfig.json`, which is not ideal long-term. Exclusions do not apply to files that are imported from a non-excluded file, so this effectively excludes everything that isn't included in the bundle. We will want to remove this exclusion before release.

## Testing this Branch

1. Pull the branch
2. `yarn install`
3. `yarn start`

Make sure to run `yarn test` as well.

We need a windows user to pull this branch and make sure that I didn't break anything with paths.

## Enabling Support for a DF Spec

1. Remove the `exclude` line for the spec and class from `tsconfig.json`.
2. Un-comment the import/export lines for the spec in `src/parser/index.ts`.
3. Fix all missing/invalid talent imports. Delete liberally.
4. Re-enable all of the spec's skipped tests and fix any issues with them. Delete if they test now-dead code.
5. You are now prepared to work on Dragonflight support :)

### CODE REVIEW

**Comment by emallson** [comment]
@Pewtro it wouldn't let me set the merge target to your branch, so this is a fully separate PR.

**Review by rp4rk — APPROVED** [review]
full send

**Review by kfinch — APPROVED** [review]
I mean sure why not lol

**Comment by danny-janse** [comment]
Windows (11) user here;

* Yarn properly installs
* Application starts
* Following classic classes do not work;
  * Hunter 
image
  * Other classes had no issues

`yarn test` summary
image

I did noticed that the analysis folder in the root still exists after checking out this PR. This is due to the node_modules folders created for each subfolder. All of these folders were empty and could be safely removed.

Everything else seems to work as intended.

**Comment by emallson** [comment]
I also tested and this does appear to fix the auto-import issues

**Comment by kfinch** [comment]
Windows user here. I just pulled the branch and used `yarn start` and `yarn test`. 'Start' launched the website without issues, and all the (activated) tests passed.

When looking at the code in WebStorm I am having a lot of import errors however.

**Comment by kfinch** [comment]
After removing the exclude in tsconfig, my IDE loads spec stuff properly

**Comment by emallson** [comment]
After digging around, import errors seen by @kfinch and @darthelit seem to be related to the tsconfig exclusion of spec folders. Once you remove the exclusions, they go away. Moved that step up to #1 in the instructions. going to merge

**Pull request merged**
