### PR TITLE
[Brewmaster Monk] [Bug] Checklist fix

### PR DESCRIPTION
**Pull request by joshinat0r**
Checklist failed when a player wasn't using Rushing Jade Wind. This will disable the requirement check when the player wasn't using RJW

### CODE REVIEW

**Comment by joshinat0r** [comment]
You're sure about that? RJW has a custom threshold based on its module (essentially checking the uptime), its not a simple "kept it on cooldown"-suggestion

**Comment by sMteX** [comment]
I know, it's just a matter of syntax - what I mean is you don't need ternary operator but just `&&`, and the `React.Fragment <>` is redundant if the only thing inside is another React component. The example was just to show what I mean, not that you should be using `AbilityRequirement`.

**Comment by joshinat0r** [comment]
Oh, yeah you're right. Just blindly coppied emallsons code. Updated the other ones aswell

**Comment by joshinat0r** [comment]
The fragment isn't redundant, the `uptime` makes the parent-element mandatory.
And the parentheses are necessary for multi-line JSX (at least eslint is complaining about it locally)

**Pull request merged**
