### PR TITLE
Fix early DoT refresh extension check

### PR DESCRIPTION
**Pull request by layday**
The sign was flipped having the opposite
effect than was intended.

### CODE REVIEW

**Comment by layday** [comment]
Presumably, `effective` should also be equal to `maxDuration` but I don't know if that might break something that relies on the incorrect calculation.

**Comment by layday** [comment]
Rebased.

**Comment by MikeCook9994** [comment]
I think there's something else wrong with this module that I can't figure out. I took your changes to EarlyDotRefreshes.js tab and tried them locally with the changes I'm working on for ele flame shock early refreshes. I used [this](https://www.warcraftlogs.com/reports/TX1fWKC2h3DjvRHa#fight=18&type=casts&source=23&translate=true&ability=188389) log to check against. The flame shock cast at 1:25 is absolutely an early refresh but is not identified as such.

**Comment by layday** [comment]
@MikeCook9994, it works fine for me:

Screenshot 2019-10-20 at 13 13 22

... using:

```diff
diff --git a/src/parser/shaman/elemental/CombatLogParser.js b/src/parser/shaman/elemental/CombatLogParser.js
index df8938ec0..86c05e5b8 100644
--- a/src/parser/shaman/elemental/CombatLogParser.js
+++ b/src/parser/shaman/elemental/CombatLogParser.js
@@ -4,6 +4,7 @@ import Abilities from './modules/Abilities';
 import CancelledCasts from './modules/features/CancelledCasts';
 import AlwaysBeCasting from './modules/features/AlwaysBeCasting';
 import Overload from './modules/features/Overload';
+import EarlyDotRefreshes from './modules/features/EarlyDotRefreshes';
 
 import FlameShock from './modules/core/FlameShock';
 import LavaSurge from './modules/core/LavaSurge';
@@ -50,6 +51,7 @@ class CombatLogParser extends CoreCombatLogParser {
     flameShock: FlameShock,
     lavaSurge: LavaSurge,
     overload: Overload,
+    earlyDotRefreshes: EarlyDotRefreshes,
     stormfireElemental: StormFireElemental,
     buffs: Buffs,
     cancelledCasts: CancelledCasts,
diff --git a/src/parser/shaman/elemental/modules/checklist/Module.js b/src/parser/shaman/elemental/modules/checklist/Module.js
index a05c96988..92063f206 100644
--- a/src/parser/shaman/elemental/modules/checklist/Module.js
+++ b/src/parser/shaman/elemental/modules/checklist/Module.js
@@ -8,6 +8,8 @@ import PreparationRuleAnalyzer from 'parser/shared/modules/features/Checklist/Pr
 import CancelledCasts from 'parser/shaman/elemental/modules/features/CancelledCasts';
 import AlwaysBeCasting from 'parser/shaman/elemental/modules/features/AlwaysBeCasting';
 
+import EarlyDotRefreshes from '../features/EarlyDotRefreshes';
+
 import Component from './Component';
 
 class Checklist extends BaseChecklist {
@@ -17,6 +19,7 @@ class Checklist extends BaseChecklist {
     preparationRuleAnalyzer: PreparationRuleAnalyzer,
     cancelledCasts: CancelledCasts,
     alwaysBeCasting: AlwaysBeCasting,
+    earlyDotRefreshes: EarlyDotRefreshes,
   };
 
   render() {
@@ -28,6 +31,7 @@ class Checklist extends BaseChecklist {
           ...this.preparationRuleAnalyzer.thresholds,
           cancelledCasts: this.cancelledCasts.cancelledCastSuggestionThresholds,
           downtime: this.alwaysBeCasting.downtimeSuggestionThresholds,
+          flameShockRefresh: this.earlyDotRefreshes.suggestionThresholdsFlameShockEfficiency,
         }}
       />
     );
diff --git a/src/parser/shaman/elemental/modules/features/EarlyDotRefreshes.js b/src/parser/shaman/elemental/modules/features/EarlyDotRefreshes.js
new file mode 100644
index 000000000..b356559f1
--- /dev/null
+++ b/src/parser/shaman/elemental/modules/features/EarlyDotRefreshes.js
@@ -0,0 +1,54 @@
+import SPELLS from 'common/SPELLS';
+
+import EarlyDotRefreshesCore from 'parser/shared/modules/earlydotrefreshes/EarlyDotRefreshes';
+import suggest from 'parser/shared/modules/earlydotrefreshes/EarlyDotRefreshesSuggestionByCount';
+
+const DOTS = [
+  {
+    name: 'Flame Shock',
+    debuffId: SPELLS.FLAME_SHOCK.id,
+    castId: SPELLS.FLAME_SHOCK.id,
+    duration: 24000,
+  },
+];
+
+const MINOR_THRESHOLD = 0.9;
+const AVERAGE_THRESHOLD = 0.8;
+const MAJOR_THRESHOLD = 0.6;
+
+class EarlyDotRefreshes extends EarlyDotRefreshesCore {
+  static dots = DOTS;
+
+  get suggestionThresholdsFlameShock() {
+    return {
+      spell: SPELLS.FLAME_SHOCK,
+      count: this.casts[DOTS[0].castId].badCasts,
+      actual: this.badCastsPercent(DOTS[0].castId),
+      isGreaterThan: {
+        minor: 1 - MINOR_THRESHOLD,
+        average: 1 - AVERAGE_THRESHOLD,
+        major: 1 - MAJOR_THRESHOLD,
+      },
+      style: 'percentage',
+    };
+  }
+
+  get suggestionThresholdsFlameShockEfficiency() {
+    return {
+      spell: SPELLS.FLAME_SHOCK,
+      actual: 1 - this.badCastsPercent(DOTS[0].castId),
+      isLessThan: {
+        minor: MINOR_THRESHOLD,
+        average: AVERAGE_THRESHOLD,
+        major: MAJOR_THRESHOLD,
+      },
+      style: 'percentage',
+    };
+  }
+
+  suggestions(when) {
+    suggest(when, this.suggestionThresholdsFlameShock);
+  }
+}
+
+export default EarlyDotRefreshes;
```

**Comment by MikeCook9994** [comment]
@layday So my problem was that I was using the instants version of the early dot refreshes analyzers. But flame shock is an instant cast (but with a cooldown compared to moon/sunfire).

**Comment by layday** [comment]
Then I suppose it wasn't picked up as a bad cast because they were on the move (or the model thinks they were on the move).

**Comment by layday** [comment]
(I imagine for elemental shamans it would be more efficient to use Frost Shock when moving than refresh Flame Shock outside of pandemic, so you could simply use `EarlyDotRefreshesCore` or override `betterFillersAvailable`.)

**Comment by MikeCook9994** [comment]
I overrode betterFillersAvailable to always return false for that reason.

**Comment by HawkCorrigan** [comment]
Second thing
The difference between early refreshing FS and casting FrS is really hard to pinpoint because it depends entirely on fight timers. If you don't lose a GCD early refreshing is always better.

**Comment by layday** [comment]
Well, there's no reason to revert anything, but I've made the suggested change.

**Comment by layday** [comment]
Well, I'm not rebasing again.  Somebody with write access can just fix it when they get the chance.

**Comment by MartijnHols** [comment]
Don't worry about rebasing, anyone with merge access can fix that when they're ready to merge. I'd like @HawkCorrigan to give his ok before doing so though, since he knows this code better.

**Comment by MartijnHols** [comment]
For your information the process is as follows. Basically GitHub shows us this when there's a conflict instead of the merge button:
image
Clicking the button brings us to an editable field where we can fix the conflict;
image
We can easily fix it by just removing the conflict indicators (the lines with the arrows and ====), and then we can also fix the changelog entry date. A contributor then just hits "Commit" and then everything is ready to merge. It makes sense to only do this once when we're ready to merge, so again no need to worry about it.

ps. thanks a lot for the PR!

**Comment by emallson** [comment]
@HawkCorrigan any movement on this?

**Comment by layday** [comment]
Is there nobody else capable of reviewing swapping two variables around?  If we are that worried about correctness that we've kept this open closing in on two months perhaps a better course of action would've been to add some unit tests.

**Comment by abelito75** [comment]
Well you see even if we want to right now we physically can't merge it as there are merge conflicts as Zero has mentioned before. 
image
I'm not sure if you had fixed these and no one had noticed a change or what but these are physically blocking us right now.

**Comment by layday** [comment]
I was told the person merging would take care of the conflicts: “anyone with merge access can easily fix changelog conflicts when they're ready to merge”. Is there anything you need me to do?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by abelito75** [comment]
We can easily do it but it is quite easy for you to fix this too

**Comment by emallson** [comment]
There appeared to be some actual questions about the approach? I can't
super tell. I wouldn't work about fixing the CHANGELOG file. We can do that
when the rest is approved

**Comment by layday** [comment]
Originally I'd flipped the signs - you can't see this now because I squashed the commits when I rebased - before I was asked to swap the variables around, which I've done.  The end result was the same.

**Comment by MartijnHols** [comment]
> Is there nobody else capable of reviewing swapping two variables around? If we are that worried about correctness that we've kept this open closing in on two months perhaps a better course of action would've been to add some unit tests.

That's fair. First off, I am sorry for leaving this PR open for so long. I should have monitored it more closely and help figure out the correctness.

You’re right that we’re slightly worried about correctness, and unit tests would definitely help. We have chosen to make tests optional so maintainers can decide for themselves as not everyone is as inclined to write them. This project requires a lot of active maintainers to stay up-to-date, so we have to keep the barrier of contributing low. I’ve since grown lax and omitted tests for most core as well. This does make a lot of the code hard to work with.

For decent certainty when making changes or improvements to the core or shared modules, we have “integration tests” that take an entire log and generate a snapshot of all module output. This shows us what is affected and how. Right now your changes have no impact on any of the specs using these integration tests, so it doesn’t seem to break anything but that might also be an indication of a lack of a relevant test.

I’ll add one for the Elemental Shaman log mentioned above and update this PR with a new snapshot so we can see what exactly this changes. If it makes sense I’ll go ahead and merge this. We should probably add a log like this for every spec, as seeing the impact of changes over multiple specs will give us a lot more confidence.

Thanks a lot for your contribution so far and your feedback. Again I am terribly sorry for taking so long with the review. Please do not hesitate to ping me in the future if a PR review takes long if you’re still willing to try to make another contribution.

@abelito75 the merge conflicts are no problem. They can easily be resolved with the GitHub interface as I explained on October 25th. There’s no need for PR submitters to keep updating from master as there’s no telling when a reviewer considers the PR ready for merging.

**Comment by MartijnHols** [comment]
I'm having a hard time verifying if https://github.com/WoWAnalyzer/WoWAnalyzer/pull/3368/files#diff-99643caa8dc66c6140747e4fcb2d8fcc matches expectations and I have to go. If anyone can verify these then please merge, otherwise I'll look again tomorrow evening.

**Comment by abelito75** [comment]
@MartijnHols From all the times I had merge conflicts of this nature (even before I could merge things myself) I had been told to fix them myself and did through githubs interface

**Comment by emallson** [comment]
got to admit, i didn't actually read the PR when I pinged people. With these, its generally easier to let the people that were already involved finish it out. In this case, the PR is very simple so there isn't really a need. I had some time, so I've reviewed it. Not sure why it got held up this long. The snapshot results look OK to me (the log is: https://www.warcraftlogs.com/reports/TX1fWKC2h3DjvRHa#fight=18&type=casts&translate=true&pins=0%24Separate%24%23244F4B%24auras-gained%241%240.0.0.Any%2465044208.0.0.Shaman%24true%240.0.0.Any%24false%24188389&source=23&ability=188389&view=events)

**Comment by layday** [comment]
Thanks for merging and thanks for taking the time to explain Martijn.

**Comment by layday** [comment]
@abelito75, I was not able to interact with the GitHub interface.

**Comment by abelito75** [comment]
Oof. Idk the difference then since my early prs I had to change the change log and I was able to use github's interface

**Pull request merged**
