### PR TITLE
Fixing CanceledCasts module

### PR DESCRIPTION
**Pull request by TJMoats**
I guess a linter got to this code?

### CODE REVIEW

**Comment by emallson** [comment]
`for...of` should work fine here. what happened?

**Comment by TJMoats** [comment]
for...of works if you don't index the object. I will switch it to use for of.

**Comment by emallson** [comment]
That is weird. I guess for of converts keys to strings? May be better to just switch this to `Object.values(this.canceledCasts).reduce((a, b) => a + b));` (and a `.map` call in the latter section) rather than fighting the linter on this.

**Comment by TJMoats** [comment]
`for...in` uses the index of the thing you are iterating over
`for...of` uses the value of the thing

There is no (easy) way to get an index out of `for...of` which is why this used `for...in` initially.

```
const foo = {1: "a", 2: "b", 3: "c"}
for (const bar in foo){
  console.log(bar) // outputs 1 2 3
  console.log(foo[bar]) // outputs "a" "b" "c"
}

// foo is not iterable because we are using an object, not an array. Objects are not iterable by default.
// This will throw an error
for (const baz of foo){
  console.log(baz)
}
```

```
const foo_array = ["a", "b", "c"]
for (const bar in foo_array){
  console.log(bar) // outputs 0 1 2
  console.log(foo_array[bar]) // outputs "a" "b" "c"
}

// foo is iterable because we are using an array.
// This will not throw an error
for (const baz of foo_array){
  console.log(baz)  // outputs "a" "b" "c"
}
```

**Comment by emallson** [comment]
Ah, that'd explain it. I don't use for loops that often in js anymore...partly because of nonsense like this.

**Pull request merged**
