### PR TITLE
[Windwalker] Update Spinning Crane Kick

### PR DESCRIPTION
**Pull request by Juko8**
image

Suggestions regarding bad casts were inaccurate and misleading, and have therefore been removed

### CODE REVIEW

**Comment by abelito75** [comment]
Is average hits the average damage tics ticks or average number of mobs hit?

**Comment by Juko8** [comment]
It counts all ticks @abelito75

**Comment by abelito75** [comment]
Sounds good to be

**Comment by emallson** [comment]
@abelito75 if you're gonna review actually make a review :anger:

**Comment by abelito75** [comment]
It was a question >:(

**Pull request merged**
