### PR TITLE
Adding defensive usage guide to demo warlock

### PR DESCRIPTION
**Pull request by ZyerTCoder**
### Description

Added a defensive guide section to the shared warlock modules
Added Dark Pact
Added Unending Resolve
Added damage taken timeline and casts breakdown
Dark Pact analyzer remakes the AllCooldownUsageList component

Added extra exports to AllCooldownUsagesList
Added subsection title to AllCooldownUsagesList (still shows up if you hide the explanation)

### Testing
[smolderon](http://localhost:3000/report/myndpGBw3k7rjVDf/4-Mythic+Smolderon+-+Kill+(7:01)/Yumiblood/standard/overview)
[m+](http://localhost:3000/report/g6Zm8BWhjkGA7MVQ/7-Mythic++Atal'Dazar+-+Kill+(25:28)/Fuitclaudit/standard/overview)
[fyrakk](http://localhost:3000/report/L8c23DzkWHvgtbKB/33-Mythic+Fyrakk+the+Blazing+-+Wipe+31+(8:31)/Yumiblood/standard)
[destro](http://localhost:3000/report/kQbaNq9XDZLFyTCj/31-Mythic+Smolderon+-+Kill+(5:50)/Splatlack/standard/statistics)
[aff](http://localhost:3000/report/TkAwcG2dF6hmBvCx/27-Mythic+Smolderon+-+Kill+(6:39)/Slayroth/standard/overview)

#### Other AllCooldownUsagesList users
[prot pala](http://localhost:3000/report/kKVw18ZnNxCTpDtR/33-Mythic+Fyrakk+the+Blazing+-+Wipe+33+(7:00)/Thatscr%C3%A4zy/standard)
[vdh](http://localhost:3000/report/dFzCLcjyqMbX43KP/20-Mythic+Volcoross+-+Kill+(3:11)/Toppledh/standard)
[guardian](http://localhost:3000/report/VWt9ZTmxfhQyLw14/9/11)
[brewmaster](http://localhost:3000/report/mLcvBXz6YVwTZ2QG/24-Mythic+Volcoross+-+Kill+(4:43)/Cobaro/standard)

image

### CODE REVIEW

**Comment by emallson** [comment]
what's your reasoning for duplicating the top-level `AllCooldownUsageList` component into your `DarkPact` analyzer?

**Comment by ZyerTCoder** [comment]
> what's your reasoning for duplicating the top-level `AllCooldownUsageList` component into your `DarkPact` analyzer?

Removing the SmallPassFailBar since the styling didn't match the MitigationTooltipSegment and adding the relevant usage info for Dark Pact (hp when used, shield size and unused) which couldn't fit the existing "mitigation by talent" set up

**Comment by emallson** [comment]
rather than duplicating the entire component, it is probably better to add an option to just disable the bit you don't want, and to relabel the remaining section

**Comment by emallson** [comment]
There's a potential refactor here to have allow the above-the-~~fold~~ header stuff to be customized more than is currently possible

**Comment by ZyerTCoder** [comment]
Agreed, but I'm not familiar enough with React or the rest of WoWA to refactor whole components whilst making sure it doesn't accidentally brick anyone else using it

**Comment by Krealle** [comment]
One thing that stands out to me is the size of the bars you are using. They seem to almost overlap eachother due to how big they are, compared to the already implemented examples provided. You might want to make them a bit thinner to improve clarity.

edit: Doesn't seem to happen when I run it locally, so must just be your browser.

**Comment by ZyerTCoder** [comment]
> edit: Doesn't seem to happen when I run it locally, so must just be your browser.

Looks the same on both my Chrome and Edge, not to mention I didn't change the bar component.
What does it look like to you?

**Comment by Krealle** [comment]
Was just refering to the screenshots you posted. The bars looked pretty big there.
Bars look like this on my end.
image

**Pull request merged**
