### PR TITLE
Add all remaining legendaries

### PR DESCRIPTION
**Pull request by avilene**
This should be it for #388: List all legendaries in item.

### CODE REVIEW

**Comment by MartijnHols** [comment]
Nice thanks! 👍 

What was actually meant with the issue was to show all items in the items box, such as for this log: https://wowanalyzer.com/report/kpLwvNVqCWZfMxHP/21-Mythic+Sisters+of+the+Moon+-+Kill+(7:38)/리로리로리:
image

This person has 2 legendaries equipped but since they're not being actively analysed they're not shown. The requested feature is to just show the legendaries regardless of them being equipped. So I'll merge this but leave the issue open for now.  Thanks again!

**Review by MartijnHols — APPROVED** [review]

**Comment by fyruna** [comment]
@MartijnHols If i understand it correctly the idea is to show all the applicable legendaries in that box even if they aren't equipped? That would clutter it for quite a few players.

**Comment by MartijnHols** [comment]
It will only show the 2 (soon 3) that are equipped, which are almost always relevant to analysis.

**Comment by fyruna** [comment]
Okay I'll make it work!

**Pull request merged**
