### PR TITLE
[Server] Remove bad dependency from event-stream and update version

### PR DESCRIPTION
**Pull request by Dambroda**
Just testing if this resolves Travis errors.  Travis is bugging out now that flatmap has been removed from npm (see below). New version of event-stream has flatmap removed. I just manually updated the version number and removed the dep to match the npm description, but I assume there's a command I should have run instead that also updates the crc? 

Cause: https://github.com/dominictarr/event-stream/issues/115

### CODE REVIEW

**Comment by MartijnHols** [comment]
cd server
npm install
npm audit fix

**Comment by MartijnHols** [comment]
fixed by 0ec23b772abeadd57fd56e46ede439ed7f442de5

I wasn't sure if your PR had really fixed the issue

**Comment by Dambroda** [comment]
fully expected it, I dont really know how to resolve any npm issues that may come up 👍

**Comment by MartijnHols** [comment]
Might have been that it fixed things, just missing the guarantees. Especially since v4 of the package was published by the same person who published the compromised version. And a major version bump generally breaks something.

**Pull request closed without merging**
